name: flash_chat
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  animated_text_kit: ^2.0.0
  firebase_core: ^0.4.4
  firebase_auth: ^0.15.4
  firebase_storage: ^3.1.1
  cloud_firestore: ^0.13.3
  modal_progress_hud: ^0.1.3
  emoji_picker: ^0.1.0
  rflutter_alert: ^1.0.3

  ##toast, cache data local, image pick and cache network image and parse date time
  fluttertoast: ^3.1.3
  shared_preferences: ^0.5.6+2
  image_picker: ^0.6.3+4
  cached_network_image: ^2.0.0
  intl: ^0.16.1




dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - images/
